# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  TuiScreen_config = debug

else ifeq ($(config),release)
  TuiScreen_config = release

else ifeq ($(config),dist)
  TuiScreen_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := TuiScreen

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

TuiScreen:
ifneq (,$(TuiScreen_config))
	@echo "==== Building TuiScreen ($(TuiScreen_config)) ===="
	@${MAKE} --no-print-directory -C . -f TuiScreen.make config=$(TuiScreen_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f TuiScreen.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   TuiScreen"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"