#pragma once

enum wrap_mode
{
	TUI_WRAP_MODE_IGNORE,
	TUI_WRAP_MODE_LOOP,
};

enum screen_origin
{
	TUI_SCREEN_ORIGIN_TOP_LEFT,
	TUI_SCREEN_ORIGIN_BOTTOM_LEFT,
	TUI_SCREEN_ORIGIN_TOP_RIGHT,
	TUI_SCREEN_ORIGIN_BOTTOM_RIGHT,
	TUI_SCREEN_ORIGIN_CENTER,
};

enum sprite_origin
{
	TUI_SPRITE_ORIGIN_TOP_LEFT,
	TUI_SPRITE_ORIGIN_BOTTOM_LEFT,
	TUI_SPRITE_ORIGIN_TOP_RIGHT,
	TUI_SPRITE_ORIGIN_BOTTOM_RIGHT,
	TUI_SPRITE_ORIGIN_CENTER,
};